spring.application.name=habitTracker
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/habitflow
spring.datasource.username=habituser
spring.datasource.password=habitpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openai.api.key=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

huggingface.api.key=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

cohere.api.key=0RvSMpEygKFh1uxW9BDIRz1xyR4RuUWl9qH5jyzl